export const WORK_TYPE_OPTIONS: Record<string, string[]> = {
  Model: [
    "Editorial",
    "Runway",
    "Beauty",
    "Commercial",
    "Lifestyle",
    "Swimwear",
    "Lingerie",
    "Fit Modeling",
    "Alternative",
    "Art Nude",
    "Music Video",
    "Performance",
  ],
  Photographer: [
    "Editorial",
    "Portraits",
    "Beauty",
    "Commercial",
    "Lookbook",
    "Campaign",
    "Nightlife",
    "BTS",
    "Studio",
    "Fashion",
    "Test Shoots",
    "Event Coverage",
  ],
  Videographer: [
    "Fashion Film",
    "BTS",
    "Commercial",
    "Campaign",
    "Music Video",
    "Nightlife",
    "Event Coverage",
    "Interviews",
    "Studio Sessions",
    "Social Clips",
    "Performance",
    "Documentary",
  ],
  "Makeup Artist": [
    "Beauty",
    "Editorial",
    "Bridal",
    "SFX",
    "Body Paint",
    "Runway",
    "Campaign",
    "Nightlife",
    "Film / Video",
    "Photoshoots",
  ],
  Stylist: [
    "Wardrobe Styling",
    "Editorial",
    "Lookbook",
    "Runway",
    "Vintage Pulls",
    "Campaign",
    "Nightlife",
    "Commercial",
    "Costume Styling",
  ],
  Retoucher: [
    "Beauty Retouch",
    "Skin Retouch",
    "Fashion Retouch",
    "Compositing",
    "Campaign Cleanup",
    "Color Finishing",
    "Editorial Retouch",
  ],
  "Set Designer": [
    "Editorial Builds",
    "Props",
    "Production Design",
    "Installations",
    "Window / Display",
    "Campaign Sets",
    "Nightlife Environments",
  ],
  "Creative Director": [
    "Campaign Direction",
    "Editorial Direction",
    "Casting",
    "Brand Concepts",
    "Shoot Concepts",
    "Visual Identity",
    "Art Direction",
  ],
  "Wardrobe Stylist": [
    "Editorial Pulls",
    "Runway",
    "Tailoring",
    "Lookbook",
    "Vintage Pulls",
    "Commercial Styling",
  ],
  "Hair Artist": [
    "Editorial Hair",
    "Color",
    "Texture",
    "Wigs",
    "Beauty",
    "Runway",
    "Film / Video",
  ],
  "Production Team": [
    "Producing",
    "PA Work",
    "Lighting",
    "Grip",
    "Studio Support",
    "Event Production",
    "Shoot Coordination",
  ],
  "Creative Professional": [
    "Editorial",
    "Campaign",
    "Beauty",
    "Collaboration",
    "Nightlife",
    "Commercial",
    "Studio",
    "Art Project",
  ],
};

export function getWorkTypeOptions(category: string) {
  return WORK_TYPE_OPTIONS[category] || WORK_TYPE_OPTIONS["Creative Professional"];
}
